services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - PORT=${APP_PORT}
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-entrypoint.sh:/prometheus-entrypoint.sh
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - app-network
    environment:
      - REMOTE_WRITE_URL=${REMOTE_WRITE_URL}
      - X_API_KEY=${X_API_KEY}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
      - APP_PORT=${APP_PORT}
    entrypoint: ["/bin/sh", "/prometheus-entrypoint.sh"]

networks:
  app-network:
    driver: bridge
