global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'go-app'
    static_configs:
      - targets: ['go-app:${APP_PORT}']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:${PROMETHEUS_PORT}']

remote_write:
  - url: "${REMOTE_WRITE_URL}"
    headers:
      X-API-KEY: "${X_API_KEY}"
